export const actionTypes = {
    SET_VEHICLES: "SET_VEHICLES",
    SET_NEXT_PAGE_OF_VEHICLES: "SET_NEXT_PAGE_OF_VEHICLES",
    SET_SEARCH_VEHICLES: "SET_SEARCH_VEHICLES",
    SET_TOTAL_INFO_OF_VEHICLES: "SET_TOTAL_INFO_OF_VEHICLES",
};