export const actionTypes = {
    GET_VEHICLES: "GET_VEHICLES",
    ADD_NEXT_PAGE_OF_VEHICLES: "ADD_NEXT_PAGE_OF_VEHICLES",
    SEARCH_VEHICLES: "SEARCH_VEHICLES",
    GET_TOTAL_INFO_OF_VEHICLES: "GET_TOTAL_INFO_OF_VEHICLES",
};