export const actionTypes = {
    SET_PEOPLE: "SET_PEOPLE",
    SET_NEXT_PAGE_OF_PEOPLE: "SET_NEXT_PAGE_OF_PEOPLE",
    SET_SEARCH_PEOPLE: "SET_SEARCH_PEOPLE",
    SET_TOTAL_INFO_OF_PEOPLE: "SET_TOTAL_INFO_OF_PEOPLE",
};