export const actionTypesSaga = {
    GET_PEOPLE: "GET_PEOPLE",
    ADD_NEXT_PAGE_OF_PEOPLE: "ADD_NEXT_PAGE_OF_PEOPLE",
    SEARCH_PEOPLE: "SEARCH_PEOPLE",
    GET_TOTAL_INFO_OF_PEOPLE: "GET_TOTAL_INFO_OF_PEOPLE"
};