export const actionTypes = {
    GET_STARSHIPS: "GET_STARSHIPS",
    ADD_NEXT_PAGE_OF_STARSHIPS: "ADD_NEXT_PAGE_OF_STARSHIPS",
    SEARCH_STARSHIPS: "SEARCH_STARSHIPS",
    GET_TOTAL_INFO_OF_STARSHIPS: "GET_TOTAL_INFO_OF_STARSHIPS",
};