export const actionTypes = {
    SET_STARSHIPS: "SET_STARSHIPS",
    SET_NEXT_PAGE_OF_STARSHIPS: "SET_NEXT_PAGE_OF_STARSHIPS",
    SET_SEARCH_STARSHIPS: "SET_SEARCH_STARSHIPS",
    SET_TOTAL_INFO_OF_STARSHIPS: "SET_TOTAL_INFO_OF_STARSHIPS",
};