export const actionTypes = {
    SET_SPECIES: "SET_SPECIES",
    SET_NEXT_PAGE_OF_SPECIES: "SET_NEXT_PAGE_OF_SPECIES",
    SET_SEARCH_SPECIES: "SET_SEARCH_SPECIES",
    SET_TOTAL_INFO_OF_SPECIES: "SET_TOTAL_INFO_OF_SPECIES",
};