export const actionTypes = {
    GET_SPECIES: "GET_SPECIES",
    ADD_NEXT_PAGE_OF_SPECIES: "ADD_NEXT_PAGE_OF_SPECIES",
    SEARCH_SPECIES: "SEARCH_SPECIES",
    GET_TOTAL_INFO_OF_SPECIES: "GET_TOTAL_INFO_OF_SPECIES",
};