export const actionTypes = {
    SET_PLANETS: "SET_PLANETS",
    SET_NEXT_PAGE_OF_PLANETS: "SET_NEXT_PAGE_OF_PLANETS",
    SET_SEARCH_PLANETS: "SET_SEARCH_PLANETS",
    SET_TOTAL_INFO_OF_PLANETS: "SET_TOTAL_INFO_OF_PLANETS",
};