export const actionTypes = {
    GET_PLANETS: "GET_PLANETS",
    ADD_NEXT_PAGE_OF_PLANETS: "ADD_NEXT_PAGE_OF_PLANETS",
    SEARCH_PLANETS: "SEARCH_PLANETS",
    GET_TOTAL_INFO_OF_PLANETS: "GET_TOTAL_INFO_OF_PLANETS",
};